"""
Utility functions. DO NOT EDIT THIS FILE.
"""
import os.path
import pickle
import time
from contextlib import contextmanager
from typing import Callable, Generator, Optional


def cache_pickle(func: Callable) -> Callable:
    """
    A decorator that caches the output of a function to a pickle file.
    It adds a keyword parameter called "cache_filename" that gives the
    name of the cached file.
    """

    def _func(*func_args, cache_filename: Optional[str] = None, **func_kwargs):
        if cache_filename is not None and os.path.isfile(cache_filename):
            message = "Loading cached function output from {}..." \
                      "".format(cache_filename)
            with timer(message):
                with open(cache_filename, "rb") as f:
                    return pickle.load(f)

        return_val = func(*func_args, **func_kwargs)

        if cache_filename is not None:
            message = "Saving function output to {}..." \
                      "".format(cache_filename)
            with timer(message):
                with open(cache_filename, "wb") as f:
                    pickle.dump(return_val, f)

        return return_val

    return _func


@contextmanager
def timer(message: str) -> Generator[Callable[[None], float], None, None]:
    """
    A timer that measures the time spent running code within a with-
    block.

    :param message: A message to be printed when the timer starts.
    :return: A generator that yields a function that returns the current
        time elapsed.
    """
    print(message)

    # Start timer
    start_time = time.time()
    yield lambda: time.time() - start_time

    # Stop timer
    end_time = time.time()
    elapsed = end_time - start_time
    print("Done. Time elapsed: {:.3f} seconds".format(elapsed))
